# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EyeofcloudDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry', '~> 1.0.2'
  pod 'ReactiveObjC', '~> 2.1.2' 
  pod 'SVProgressHUD', '~> 2.1.2'
  pod 'Eyeofcloud', '~> 1.4.4'
  # Pods for EyeofcloudDemo

end
